django_mandatory/bank_app/urls.py
from django.urls import path, include
from . import views
from .api import UserList, UserDetail, RankList, RankDetail, AccountList, AccountDetail, CustomerList, CustomerDetail, \
    TransactionList, TransactionDetail
from rest_framework.authtoken.views import obtain_auth_token

app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),

    path('customer_dashboard/', views.customer_dashboard, name='customer_dashboard'),
    path('customer_account/', views.customer_account, name='customer_account'),

    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_all_customers/', views.staff_all_customers, name='staff_all_customers'),
    path('search_customers/', views.search_customers, name='search_customers'),

    path('send_transfer_request/', views.send_transfer_request, name='send_transfer_request'),
    path('view_transfer_data/<int:pk>', views.view_transfer_data, name='view_transfer_data'),
    path('api/receive_transfer/', views.receive_transfer, name='receive_transfer'),
    path('api-token-auth/', obtain_auth_token),

    path('user/api/v1/', UserList.as_view()),
    path('user/api/v1/<int:pk>/', UserDetail.as_view()),
    path('user/api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('rank/api/v1/', RankList.as_view()),
    path('rank/api/v1/<int:pk>/', RankDetail.as_view()),
    path('rank/api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('account/api/v1/', AccountList.as_view()),
    path('account/api/v1/<int:pk>/', AccountDetail.as_view()),
    path('account/api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('customer/api/v1/', CustomerList.as_view()),
    path('customer/api/v1/<int:pk>/', CustomerDetail.as_view()),
    path('customer/api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('transaction/api/v1/', TransactionList.as_view()),
    path('transaction/api/v1/<int:pk>/', TransactionDetail.as_view()),
    path('transaction/api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
]

django_mandatory/django_mandatory/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bank_app.urls'))
]

django_mandatory/bank_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Customer, Account, TransferModel
from django.core.exceptions import ObjectDoesNotExist


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(['Username already exists.'])
        return self.cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('rank', 'phone')


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)


class TransferForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_description = forms.CharField(label='Debit Account Text', max_length=25)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_description = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data


class TransModelForm(forms.ModelForm):
    state = forms.BooleanField(label='Is last update', required=False)

    class Meta:
        model = TransferModel
        fields = ('amount', 'debit_account', 'debit_description', 'credit_account', 'credit_description')

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.cleaned_data.get('state'):
            instance.state = TransferModel.StateEnum.CREATED
        else:
            instance.state = TransferModel.StateEnum.PENDING
        if commit:
            instance.save()
        return instance

      
class SearchCustomers(forms.Form):
    search_query = forms.CharField(label="Search For Customer", max_length=40)

django_mandatory/bank_app/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from decimal import Decimal
from django.shortcuts import render, get_object_or_404, reverse
from .forms import NewUserForm, CustomerForm, UserForm, NewAccountForm, TransferForm, TransModelForm
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from .models import Account, Customer, Transaction, TransferModel
from django.db import IntegrityError
from secrets import token_urlsafe
from .errors import InsufficientFunds, NotAuthenticatedAPI, PostException, PutException, TransferError
from rest_framework.decorators import api_view
from rest_framework.response import Response
import requests
import time
from django.core.mail import send_mail
from django.conf import settings
from rest_framework.authtoken.models import Token
from .serializers import TransferModelSerializer


@login_required
def index(request):
    return HttpResponseRedirect('customer_dashboard')


@login_required
def customer_dashboard(request):
    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }

    return render(request, 'bank/customer_dashboard.html', context)


@login_required
def staff_new_customer(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_user_form = NewUserForm(request.POST)
        customer_form = CustomerForm(request.POST)
        if new_user_form.is_valid() and customer_form.is_valid():
            username = new_user_form.cleaned_data['username']
            first_name = new_user_form.cleaned_data['first_name']
            last_name = new_user_form.cleaned_data['last_name']
            email = new_user_form.cleaned_data['email']
            password = token_urlsafe(16)
            rank = customer_form.cleaned_data['rank']
            phone = customer_form.cleaned_data['phone']
            try:
                user = User.objects.create_user(
                        username=username,
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                )
                print(f'********** Username: {username} -- Password: {password}')
                Customer.objects.create(user=user, rank=rank, phone=phone)
                send_welcome_email(user)
                return staff_customer_details(request, user.pk)
            except IntegrityError:
                context = {
                    'title': 'Database Error',
                    'error': 'User could not be created.'
                }
                return render(request, '/', context)
    else:
        new_user_form = NewUserForm()
        customer_form = CustomerForm()
    context = {
        'new_user_form': new_user_form,
        'customer_form': customer_form,
    }
    return render(request, 'bank/staff_new_customer.html', context)


def send_welcome_email(user):
    subject = f'Welcome to kea bank {user.username}'
    message = 'Welcome to kea bank.\n\nThank you for joining.\nAn account has automaticly been made for you.' \
              '\nRegards from KEA Bank'
    from_email = 'KeaBank@Bank.dk'
    to_email = [user.email]
    return send_mail(subject, message, from_email, to_email, fail_silently=False)


@login_required
def staff_customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=customer.user)
        customer_form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        user_form = UserForm(request.POST, instance=customer.user)
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    new_account_form = NewAccountForm()
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'new_account_form': new_account_form,
    }
    return render(request, 'bank/staff_customer_details.html', context)


@login_required
def staff_all_customers(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customers =  Customer.objects.select_related('user').all()[:10]

    context = {
        'customers' : customers
    }

    return render(request, 'bank/all_customers.html', context)


@login_required
def search_customers(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    search_query = request.GET.get('search_query')
    
    if not search_query:
        search_query = ''

    users = User.objects.filter(username__contains=search_query).filter(email__contains=search_query)

    context = {
        'users' : users,
        'search_query' : search_query
    }

    return render(request, 'bank/search_customers.html', context)


@login_required
def staff_new_account_partial(request, user):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_account_form = NewAccountForm(request.POST)
        if new_account_form.is_valid():
            Account.objects.create(user=User.objects.get(pk=user), name=new_account_form.cleaned_data['name'])
    return HttpResponseRedirect(reverse('bank_app:staff_customer_details', args=(user,)))


@login_required
def staff_account_list_partial(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank/staff_account_list_partial.html', context)


@login_required
def staff_account_details(request, pk):
    #assert request.user.is_staff, 'Customer user routing staff view.'

    account = get_object_or_404(Account, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank/account_details.html', context)


@login_required
def transaction_details(request, transaction):
    movements = Transaction.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'bank/transaction_details.html', context)


@login_required
def account_details(request, pk):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    account = get_object_or_404(Account, user=request.user, pk=pk)
    context = {
        'account': account,
    }
    print(context)
    return render(request, 'bank/account_details.html', context)


@login_required
def customer_account(request):
    return render(request, 'bank/customer_account.html')


@login_required
def make_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts
        print(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_description = form.cleaned_data['debit_description']
            credit_account = Account.objects.get(pk=form.cleaned_data['credit_account'])
            credit_description = form.cleaned_data['credit_description']
            try:
                transfer = Transaction.transfer(amount, debit_account, debit_description,
                                                credit_account, credit_description)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank/error.html', context)
    else:
        form = TransferForm()
        form.fields['debit_account'].queryset = request.user.customer.accounts
        context = {
            'form': form,
        }
    return render(request, 'bank/make_transfer.html', context)


@login_required
def transaction_details(request, transaction):
    movements = Transaction.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'bank/transaction_details.html', context)


@login_required
def make_loan(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if not request.user.customer.can_make_loan:
        context = {
            'title': 'Create Loan Error',
            'error': 'Loan could not be completed.'
        }
        return render(request, 'bank/error.html', context)
    if request.method == 'POST':
        request.user.customer.make_loan(Decimal(request.POST['amount']), request.POST['name'])
        return HttpResponseRedirect(reverse('bank_app:customer_dashboard'))
    return render(request, 'bank/make_loan.html', {})


# ------ FOREIGN TRANSFER ----  --

# --- Bank A ---
def send_transfer_request(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'
    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts
        if form.is_valid():
            try:

django_mandatory/bank_app/templates/bank/account_details.html
{% extends "base.html" %}

{% block main %}

{% if user.is_staff %}
<p>Welcome, {{ user.username }}.</p>
{% else %}
<p>Welcome, {{ user.customer.full_name }}.</p>
{% endif %}
<article>
    <p><Strong>Date Joined: </Strong>{{user.date_joined}}</p>

    {% if user.is_staff %}

    <p><strong>This user is a staff</strong></p>

    {% endif %}
</article>
<article>
    <h3>Account Details</h3>

    <table>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Balance</th>
        </tr>
        <tr>
            <td>{{ account.pk }}</td>
            <td>{{ account.name }}</td>
            <td class="amount">{{ account.balance|floatformat:"2" }}</td>
        </tr>
    </table>
</article>

<article>
    <h3>Account Transactions</h3>
    <table>
        <tr>
            <th>Transaction UID</th>
            <th>Amount</th>
            <th>Date and Time</th>
            <th>Text</th>
        </tr>
        {% for movement in account.movements %}
        <tr>
            <td><a href="{% url 'bank_app:transaction_details' movement.transaction %}">{{ movement.transaction }}</a></td>
            <td>{{ movement.amount|floatformat:"2" }}</td>
            <td>{{ movement.date }}</td>
            <td>{{ movement.description }}</td>
        </tr>
        {% endfor %}
    </table>
</article>

{% endblock main %}

django_mandatory/bank_app/templates/bank/all_customers.html
{% extends "base.html" %}

{% block main %}

<article>
    <table>
        <thead>
            <tr>
                <td>Username</td>
                <td>Phone</td>
                <td>Rank</td>
                <td>Email</td>
                <td>First Name</td>
                <td>Last Name</td>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
                <tr>
                    <td><a href="/staff_customer_details/{{customer.id}}">{{customer.user}}</a></td>
                    <td>{{customer.phone}}</td>
                    <td>{{customer.rank}}</td>
                    <td><a href="mailto:{{customer.user.email}}">{{customer.user.email}}</a></td>
                    <td>{{customer.user.first_name}}</td>
                    <td>{{customer.user.last_name}}</td>
                </tr>
            {% endfor %}
        </tbody>
        
    </table>
</article>

{% endblock main %}

django_mandatory/bank_app/templates/bank/customer_account.html
{% extends "base.html" %}

{% block main %}
<article>


    <h1>{{ user.username }}</h1>
    <p><strong>Date joined: </strong>{{ user.date_joined }}</p>
    {% if user.is_staff %}
    <p><strong>This user is a staff</strong></p>
    {% endif %}
</article>

{% endblock main %}

django_mandatory/bank_app/templates/bank/customer_dashboard.html
{% extends "base.html" %}

{% block main %}

<article>
    {% if user.is_staff %}
    <p><strong>Welcome staff-member, {{ user.username }}</strong></p>
    {% else %}
    <p><strong>Welcome, {{ user.username }}</strong></p>
    {% endif %}
    
    {% if not user.is_staff %}
    <h3>My accounts:</h3>
    
    <table>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
        </tr>
        {% for account in accounts %}
        <tr>
            <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.pk }}</a></td>
            <td>{{ account.name }}</td>
            <td>{{ account.is_loan|yesno:"loan," }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</article>

{% endblock main %}

django_mandatory/bank_app/templates/bank/error.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customer.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock main %}

django_mandatory/bank_app/templates/bank/make_loan.html
{% extends "base.html" %}

{% block main %}
<article>
    <form action="{% url 'bank_app:make_loan' %}" method="post">
        {% csrf_token %}
        <fieldset>
        <label>
            Name for loan
            <input name="name" type="text" />
        </label>
        <label>
            Amount
            <input name="amount" />
        </label>
        <button>Submit</button>
        </fieldset>
    </form>
</article>
{% endblock main %}

django_mandatory/bank_app/templates/bank/make_transfer.html
{% extends "base.html" %}

{% block main %}
<article>
    <form action="{% url 'bank_app:make_transfer' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form }}
        <button>Log In</button>
        </fieldset>
    </form>
</article>
{% endblock main %}

django_mandatory/bank_app/templates/bank/search_customers.html
{% extends "base.html" %}

{% block main %}

<article>
    <form action="{% url 'bank_app:search_customers' %}" method="GET">
            <input type="text" name="search_query" value="{{search_query}}">
            <button>Search</button>
    </form>

    <table>
        <tr>
            <th>Customer Username</th>
            <th>Customer Full Name</th>
            <th>Email</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
            <td>{{ user.email }}</td>
        </tr>
        {% endfor %}
    </table>
</article>

{% endblock main %}

django_mandatory/bank_app/templates/bank/send_transfer_request.html
{% extends "base.html" %}

{% block main %}
<article>
    <form action="{% url 'bank_app:send_transfer_request' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form }}
        <button>Make Transfer</button>
        </fieldset>
    </form>
</article>
{% endblock main %}

django_mandatory/bank_app/templates/bank/staff_account_list_partial.html
<tbody id="account-list">
{% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
        <td>{{ account.balance|floatformat:"2" }}</td>
    </tr>
{% endfor %}
</tbody>

django_mandatory/bank_app/templates/bank/staff_customer_details.html
{% extends "base.html" %}

{% block main %}
<article>
<h3>Customer Details</h3>

<form action="{% url 'bank_app:staff_customer_details' customer.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
    <button>Update User</button>
    </fieldset>
</form>
<table>
    <thead>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Account Balance</th>
        </tr>
    </thead>
    <tbody
        id="account-list"
        hx-swap="outerHTML"
        hx-get="{% url 'bank_app:staff_account_list_partial' customer.pk %}"
        hx-trigger="load">
    </tbody>
</table>

<h3>Create New Account</h3>
<form action="{% url 'bank_app:staff_new_account_partial' customer.user.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_account_form.as_p }}
    <button>Create Account</button>
    </fieldset>
</form>
</article>
{% endblock main %}

django_mandatory/bank_app/templates/bank/staff_new_customer.html
{% extends "base.html" %}

{% block main %}
<article>
    <form action="{% url 'bank_app:staff_new_customer' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ new_user_form }}
            {{ customer_form }}
        <button>Create User</button>
        </fieldset>
    </form>
</article>
{% endblock main %}

django_mandatory/bank_app/templates/bank/transaction_details.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>Transaction Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in movements %}
    <tr>
        <td>{{ movement.account }}</td>
        <td>{{ movement.uid }}</td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.date }}</td>
        <td>{{ movement.description }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

django_mandatory/bank_app/templates/bank/view_transfer_data.html
{% extends "base.html" %}

{% block main %}

<h3>Transfer Details</h3>

<form action="{% url 'bank_app:view_transfer_data' pk=transModel.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ transfer_form }}
    <button>Update Transfer</button>
    </fieldset>
</form>
<!-- This one can be used to send patch instead
<form><button>Completede transfer</button></form>
 -->
{% endblock main %}